version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/agentforge
      - REDIS_HOST=redis
    depends_on:
      - mongo
      - redis
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379" 
